sudo: required
language: java
install: true
script: "./gradlew compileDocker"
services:
- docker
deploy:
  provider: releases
  api_key:
    secure: G8TsjBZLvSKvPqLjp7Iusxy3b9OZDsJrPA3gTdIuFFSpFI84hxK6ZzWrhPDj7W/gWyY1/m6eLeuzA795xXX/QeH8TyZSJ1ANg7woVhF/Nsvdqza4cgmJzmYRVMRcyjPsRTqsfcMRwG3iE5cHBMsRC80yX/RDN6ckfzjfXAurrarXwKIW36bz1EtjcQay3RCQu5NATIr7syOX182WMjU9Bhi4nO1zttkYnhXDuG6Er8gfLB4eiLE+hUGjQEgZPebHN9LvyIlGdlKPK84LD4CoW4UK0abpAlcjJtnBVtBZVQILkBNgiryp/lA+SfIwsoq0G1w0i8kUyVyiK5rPH64jgLzDdXTTH5jhIFUhRSg1TP0j1gJlgypJQVCsFlHN708rnjOpUknUYSYEOC9it7hsEz3m9M/mJ6ubtNswPnv2r96cmlNg9HmdhkN3413JI9uOBNd0h5GLrJJRwjFAGmlB6FItS3JVYi5myrymCLuAJifGJR+r4rQFEDCGFebmghLI8LOVx9u0+XMYUOoYQ9PAN5jgncTx6v531maM15XjIaGYaLcaK6mpMnBlcfPKFmD/TaA0t9XM2M7h141aBR8Se9BC9rtbkf4z0eV2lmkLw/73iDgZkjOwMa4HEmVLszpGRGGYVwDWG+H6JIy2XvGACVwU01IOqNykxPa9tDblc6A=
  file: build/libs/xlr-on-failure-handler-plugin-1.1.1.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-on-failure-handler-plugin
notifications:
  slack:
    secure: mEhKbkCEbNBhdkE8+EvuNVitH6UQtF1dvEDSTRZiP3ShDRzVcRsFdxZjUU7JPsKgepR5O6iDDPz3XHcVT/0jrmq6aZnrWuJbhvul0Ag8IpmD8jEINqFdsbRR5NR2ulmgm1eChela0JUotyxa9MRrNrh4MfCE/IfcgUtjl7rPq2zdYk0mqirdqG6RVkWK6Zr9UZHQx/h5pG830gEHNTbrTkLHW+6P3CICzE8OStj6VhUJfKBxEc7gQOogeYVO1nPy/nA8CfAM5UzACyzDZuEgMGzPjkpM1gRsgNWb3J1V2XWr3h90qBzVvX9E5675tTs2Dk7E/uR7deD8pk6DSNq3GeQHeLiApMd822hqelzp3ho7vhvHumEI661Y03yFGO7PEcv0uVk7Fv9U3osIDtLGEEgx6cj3c4AyhRyRewvVZgp+hStEwBhGTx4AlF1EsOBgCqIOWVe7zefM9cd99j5u2b0b6huvbksnF46iIGAevDa+aFeOXmhymDnWVKFEEzyyxEMnNHzIEvd4AlbxpkPdVixbqG8V/fZAx8YtN1Ew+wlmtqfAKU3BbxLvEgobu+VJ/mq8a/7LU784SspARUq4dgX23ukGJWNc0ucpRm+qFNsQrNh5Kk+65WImHNELAM8GaYD9TZ41OYyIOW8obQcQG4rFH02Nasx6qSlCzrWMSUA=
